version: "3.8"

services:
  nginx-openai:
    image: nginx
    container_name: nginx-openai
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf